### PR TITLE
Renamed a gsc function

### PR DESCRIPTION
**Pull request by MichaelHillcox**
Logic bitch. Please use it. 

Edit: now it's two functions!

### CODE REVIEW

**Comment by atrX** [comment]
Why rename httpPostRequest() to an ambiguous request()?

**Comment by MichaelHillcox** [comment]
Because DO IT! also just because its shorter and adding get request support would a one line if support kinda thing.

**Comment by atrX** [comment]
A name isn't better simply because it's shorter. Function names should be representative and unambiguous. httpPostRequest() was just fine.

I do agree with the other rename however.

**Comment by MichaelHillcox** [comment]
Fine. :P Although postRequest would be just fine.

**Review by atrX — APPROVED** [review]

**Review by atrX — CHANGES_REQUESTED** [review]
The function name request() is ambiguous, httpPostRequest() was just fine.

**Comment by atrX** [comment]
Woops, didn't mean to approve.

**Comment by MichaelHillcox** [comment]
fixed

**Review by atrX — COMMENTED** [review]
Approved

**Pull request merged**
